# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f <- function(v, first, last) {
    .Call(`_modSaRa2_f`, v, first, last)
}

smooth <- function(lrr, R = 10L, t = 2L) {
    .Call(`_modSaRa2_smooth`, lrr, R, t)
}

